import { useCallback, useEffect, useMemo, useState } from 'react';
import { Routes, Route, Link, useNavigate } from 'react-router-dom';
import { Activity, Archive, Building2, CheckCircle2, ClipboardList, FileText, Gauge, Mail, MoreHorizontal, Plus, Search, Send, UploadCloud, Users, X } from 'lucide-react';
import { useDropzone } from 'react-dropzone';
import imageCompression from 'browser-image-compression';
import AppShell from '../components/AppShell';
import Status from '../components/Status';
import api from '../lib/api';

const nav=[{to:'/admin',icon:Gauge,label:'Resumen'},{to:'/admin/clientes',icon:Users,label:'Clientes'},{to:'/admin/reportes',icon:ClipboardList,label:'Reportes'},{to:'/admin/documentos',icon:Archive,label:'Documentos'}];
const demoClients=[{id:2,nombre:'Corporativo Horizonte',email:'cliente@nexo.mx',activo:true,reportCount:2},{id:3,nombre:'Grupo Metrópoli',email:'operaciones@metropoli.mx',activo:true,reportCount:4},{id:4,nombre:'Industrias del Centro',email:'mantenimiento@industrias.mx',activo:false,reportCount:1}];
const demoReports=[{id:1,user_id:2,titulo:'Mantenimiento preventivo de red',tipo_servicio:'Redes y conectividad',fecha_servicio:'2026-07-18',estatus:'completado',publicado:true,tecnico:'Carlos Mendoza',client:demoClients[0]},{id:2,user_id:2,titulo:'Instalación de cámaras en acceso norte',tipo_servicio:'Videovigilancia',fecha_servicio:'2026-06-29',estatus:'completado',publicado:true,tecnico:'Mariana Torres',client:demoClients[0]},{id:3,user_id:3,titulo:'Revisión de tablero principal',tipo_servicio:'Instalación eléctrica',fecha_servicio:'2026-07-25',estatus:'programado',publicado:false,tecnico:'Luis Ortega',client:demoClients[1]}];
const dt=v=>new Date(`${v}T12:00:00`).toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'});

function useAdminData(){
  const [clients,setClients]=useState([]);const[reports,setReports]=useState([]);const[documents,setDocuments]=useState([]);const[loading,setLoading]=useState(true);
  const load=useCallback(()=>Promise.all([api.get('/admin/clientes'),api.get('/admin/reportes'),api.get('/admin/documentos')]).then(([c,r,d])=>{setClients(c.data);setReports(r.data);setDocuments(d.data)}).catch(()=>{setClients(demoClients);setReports(demoReports);setDocuments([])}).finally(()=>setLoading(false)),[]);
  useEffect(()=>{load()},[load]);return{clients,reports,documents,loading,reload:load};
}
function Head({kicker,title,action}){return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">{kicker}</p><h1 className="mt-2 font-display text-3xl font-extrabold text-navy">{title}</h1></div>{action}</div>}
function Modal({title,onClose,children,wide=false}){return <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-navy/50 p-4"><div className={`my-8 w-full ${wide?'max-w-3xl':'max-w-lg'} rounded-2xl bg-white shadow-2xl`}><div className="flex items-center justify-between border-b border-line px-6 py-5"><h2 className="font-display text-lg font-bold text-navy">{title}</h2><button onClick={onClose} className="text-slate-400"><X/></button></div>{children}</div></div>}

function Dashboard({data}){
  const stats=[['Clientes activos',data.clients.filter(c=>c.activo).length,Users,'bg-blue-50 text-blue-600'],['Reportes totales',data.reports.length,ClipboardList,'bg-violet-50 text-violet-600'],['Por publicar',data.reports.filter(r=>!r.publicado).length,Send,'bg-amber-50 text-amber-600'],['Completados',data.reports.filter(r=>r.estatus==='completado').length,CheckCircle2,'bg-emerald-50 text-emerald-600']];
  return <div><Head kicker="Vista general" title="Panel operativo"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([l,v,I,c])=><div className="card p-5" key={l}><div className={`grid h-10 w-10 place-items-center rounded-lg ${c}`}><I size={19}/></div><p className="mt-5 font-display text-3xl font-extrabold text-navy">{data.loading?'—':v}</p><p className="mt-1 text-xs font-semibold text-slate-500">{l}</p></div>)}</div>
  <div className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_.5fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><h2 className="font-display font-bold text-navy">Actividad reciente</h2><Link to="/admin/reportes" className="text-xs font-bold text-brand-600">Ver todo →</Link></div>{data.reports.slice(0,4).map(r=><div className="flex items-center gap-4 border-b border-line px-5 py-4 last:border-0" key={r.id}><span className="grid h-10 w-10 place-items-center rounded-lg bg-brand-50 text-brand-600"><Activity size={18}/></span><div className="min-w-0 flex-1"><b className="block truncate text-sm text-navy">{r.titulo}</b><small className="text-slate-500">{r.client?.nombre} · {dt(r.fecha_servicio)}</small></div><Status value={r.estatus}/></div>)}</section>
  <aside className="rounded-2xl bg-navy p-6 text-white"><UploadCloud className="text-cyan"/><h2 className="mt-8 font-display text-xl font-bold">Trabajo pendiente</h2><p className="mt-3 text-sm leading-6 text-blue-100">{data.reports.filter(r=>!r.publicado).length} reportes están en preparación antes de avisar al cliente.</p><Link to="/admin/reportes" className="mt-6 inline-block text-sm font-bold text-cyan">Revisar reportes →</Link></aside></div></div>
}

function ClientForm({close,reload}){
  const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');
  const submit=async e=>{e.preventDefault();setLoading(true);try{const{data}=await api.post('/admin/clientes',Object.fromEntries(new FormData(e.currentTarget)));setMsg(data.invitationUrl?'Invitación creada. En desarrollo, el enlace también está disponible en la respuesta.':'Cliente creado e invitación enviada.');await reload();}catch(x){setMsg(x.response?.data?.error||'No fue posible crear el cliente.')}finally{setLoading(false)}};
  return <Modal title="Nuevo cliente" onClose={close}><form onSubmit={submit} className="space-y-5 p-6"><label><span className="label">Nombre o razón social</span><input className="input" name="nombre" required/></label><label><span className="label">Correo autorizado</span><input className="input" name="email" type="email" required/></label><div className="rounded-lg bg-brand-50 p-4 text-xs leading-5 text-brand-900"><Mail size={16} className="mb-2"/>Se enviará una invitación válida por 72 horas para establecer contraseña.</div>{msg&&<p className="text-sm text-brand-700">{msg}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={close} className="btn-secondary">Cancelar</button><button disabled={loading} className="btn-primary">{loading?'Creando…':'Crear y enviar invitación'}</button></div></form></Modal>
}
function Clients({data}){
  const[open,setOpen]=useState(false);const[q,setQ]=useState('');
  const rows=data.clients.filter(c=>(c.nombre+c.email).toLowerCase().includes(q.toLowerCase()));
  const toggle=async c=>{try{await api.patch(`/admin/clientes/${c.id}`,{activo:!c.activo});await data.reload()}catch{}};
  const resend=async id=>{try{await api.post(`/admin/clientes/${id}/reenviar-invitacion`);alert('Invitación enviada.')}catch{alert('No fue posible enviar la invitación.')}};
  return <div><Head kicker="Directorio" title="Clientes" action={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={17}/> Nuevo cliente</button>}/><div className="card overflow-hidden"><div className="border-b border-line p-4"><label className="relative block max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} className="input pl-10" placeholder="Buscar cliente o correo..."/></label></div><div className="overflow-x-auto"><table className="admin-table"><thead><tr><th>Cliente</th><th>Reportes</th><th>Acceso</th><th>Acciones</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b className="block text-navy">{c.nombre}</b><small className="text-slate-500">{c.email}</small></td><td>{c.reportCount||0}</td><td><button onClick={()=>toggle(c)} className={`rounded-full px-2.5 py-1 text-xs font-bold ${c.activo?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{c.activo?'Activo':'Inactivo'}</button></td><td><button onClick={()=>resend(c.id)} className="text-xs font-bold text-brand-600">Reenviar invitación</button></td></tr>)}</tbody></table></div></div>{open&&<ClientForm close={()=>setOpen(false)} reload={data.reload}/>}</div>
}

function PhotoDrop({files,setFiles,type}){
  const onDrop=useCallback(async accepted=>{const compressed=await Promise.all(accepted.map(f=>imageCompression(f,{maxSizeMB:1,maxWidthOrHeight:1920,useWebWorker:true})));setFiles(v=>({...v,[type]:[...v[type],...compressed]}))},[setFiles,type]);
  const{getRootProps,getInputProps,isDragActive}=useDropzone({onDrop,accept:{'image/jpeg':[], 'image/png':[], 'image/webp':[]}});
  return <div><p className="label">Fotos {type}</p><div {...getRootProps()} className={`cursor-pointer rounded-xl border-2 border-dashed p-6 text-center ${isDragActive?'border-brand-500 bg-brand-50':'border-line'}`}><input {...getInputProps()}/><UploadCloud className="mx-auto text-brand-600"/><p className="mt-2 text-xs text-slate-500">Arrastra imágenes o haz clic · Se comprimen automáticamente</p></div>{files[type].length>0&&<p className="mt-2 text-xs font-semibold text-brand-600">{files[type].length} archivo(s) listo(s)</p>}</div>
}
function ReportForm({clients,close,reload}){
  const[loading,setLoading]=useState(false);const[files,setFiles]=useState({antes:[],despues:[]});const[msg,setMsg]=useState('');
  const submit=async e=>{e.preventDefault();setLoading(true);try{const payload=Object.fromEntries(new FormData(e.currentTarget));payload.user_id=Number(payload.user_id);const{data:r}=await api.post('/admin/reportes',payload);for(const type of ['antes','despues'])if(files[type].length){const fd=new FormData();fd.append('tipo',type);files[type].forEach(f=>fd.append('fotos',f));await api.post(`/admin/reportes/${r.id}/fotos`,fd)}await reload();close()}catch(x){setMsg(x.response?.data?.error||'No fue posible guardar el reporte.')}finally{setLoading(false)}};
  return <Modal title="Nuevo reporte de trabajo" onClose={close} wide><form onSubmit={submit} className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="label">Cliente</span><select name="user_id" className="input" required><option value="">Selecciona…</option>{clients.filter(c=>c.activo).map(c=><option value={c.id} key={c.id}>{c.nombre}</option>)}</select></label><label><span className="label">Fecha de servicio</span><input className="input" name="fecha_servicio" type="date" required/></label><label className="sm:col-span-2"><span className="label">Título</span><input className="input" name="titulo" required placeholder="Ej. Mantenimiento preventivo de red"/></label><label><span className="label">Tipo de servicio</span><select className="input" name="tipo_servicio"><option>Redes y conectividad</option><option>Videovigilancia</option><option>Mantenimiento integral</option><option>Instalación eléctrica</option><option>Otro</option></select></label><label><span className="label">Técnico responsable</span><input className="input" name="tecnico"/></label><label><span className="label">Estatus</span><select className="input" name="estatus"><option value="borrador">Borrador</option><option value="programado">Programado</option><option value="en_proceso">En proceso</option><option value="completado">Completado</option></select></label><span/>
  <label className="sm:col-span-2"><span className="label">Descripción</span><textarea className="input min-h-24" name="descripcion" required/></label><label><span className="label">Notas</span><textarea className="input min-h-20" name="notas"/></label><label><span className="label">Incidencias</span><textarea className="input min-h-20" name="incidencias"/></label><PhotoDrop files={files} setFiles={setFiles} type="antes"/><PhotoDrop files={files} setFiles={setFiles} type="despues"/>{msg&&<p className="sm:col-span-2 text-sm text-red-600">{msg}</p>}<div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={close} className="btn-secondary">Cancelar</button><button disabled={loading} className="btn-primary">{loading?'Guardando…':'Guardar borrador'}</button></div></form></Modal>
}
function ReportsAdmin({data}){
  const[open,setOpen]=useState(false);const[q,setQ]=useState('');const[status,setStatus]=useState('');
  const rows=useMemo(()=>data.reports.filter(r=>(!q||(r.titulo+(r.client?.nombre||'')).toLowerCase().includes(q.toLowerCase()))&&(!status||r.estatus===status)),[data.reports,q,status]);
  const publish=async id=>{if(!confirm('¿Publicar este reporte y notificar al cliente?'))return;try{await api.post(`/admin/reportes/${id}/publicar`);await data.reload()}catch{alert('No fue posible publicar el reporte.')}};
  return <div><Head kicker="Operación" title="Reportes de trabajo" action={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/> Nuevo reporte</button>}/><div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="input pl-10" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar reporte o cliente..."/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="input sm:w-48"><option value="">Todos los estatus</option><option value="borrador">Borrador</option><option value="programado">Programado</option><option value="en_proceso">En proceso</option><option value="completado">Completado</option></select></div><div className="overflow-x-auto"><table className="admin-table"><thead><tr><th>Reporte</th><th>Cliente</th><th>Fecha</th><th>Estatus</th><th>Publicación</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b className="block text-navy">{r.titulo}</b><small className="text-slate-500">{r.tipo_servicio}</small></td><td>{r.client?.nombre||'—'}</td><td>{dt(r.fecha_servicio)}</td><td><Status value={r.estatus}/></td><td>{r.publicado?<span className="text-xs font-bold text-emerald-600">Publicado</span>:<button onClick={()=>publish(r.id)} className="inline-flex items-center gap-1 text-xs font-bold text-brand-600"><Send size={14}/> Publicar</button>}</td></tr>)}</tbody></table></div></div>{open&&<ReportForm clients={data.clients} close={()=>setOpen(false)} reload={data.reload}/>}</div>
}

function DocForm({clients,close,reload}){
  const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');
  const submit=async e=>{e.preventDefault();setLoading(true);try{await api.post('/admin/documentos',new FormData(e.currentTarget));await reload();close()}catch(x){setMsg(x.response?.data?.error||'No fue posible subir el documento.')}finally{setLoading(false)}};
  return <Modal title="Publicar documento" onClose={close}><form onSubmit={submit} className="space-y-5 p-6"><label><span className="label">Cliente</span><select className="input" name="user_id" required><option value="">Selecciona…</option>{clients.map(c=><option value={c.id} key={c.id}>{c.nombre}</option>)}</select></label><label><span className="label">Título</span><input className="input" name="titulo" required/></label><label><span className="label">Categoría</span><select className="input" name="categoria"><option value="poliza">Póliza</option><option value="seguro">Seguro</option><option value="certificacion">Certificación</option><option value="otro">Otro</option></select></label><label><span className="label">Archivo PDF</span><input className="input" type="file" name="archivo" accept="application/pdf" required/></label><p className="text-xs leading-5 text-slate-500">Al publicar, el cliente recibirá una notificación por correo.</p>{msg&&<p className="text-sm text-red-600">{msg}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={close} className="btn-secondary">Cancelar</button><button disabled={loading} className="btn-primary">{loading?'Subiendo…':'Publicar documento'}</button></div></form></Modal>
}
function DocumentsAdmin({data}){
  const[open,setOpen]=useState(false);
  return <div><Head kicker="Expedientes" title="Documentos por cliente" action={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={17}/> Subir PDF</button>}/>{data.documents.length?<div className="card overflow-hidden"><table className="admin-table"><thead><tr><th>Documento</th><th>Cliente</th><th>Categoría</th><th>Fecha</th></tr></thead><tbody>{data.documents.map(d=><tr key={d.id}><td><a href={d.url} target="_blank" rel="noreferrer" className="font-bold text-brand-600">{d.titulo}</a></td><td>{d.client?.nombre}</td><td className="capitalize">{d.categoria}</td><td>{d.createdAt?dt(d.createdAt.slice(0,10)):'—'}</td></tr>)}</tbody></table></div>:<div className="card p-14 text-center"><FileText className="mx-auto text-slate-300" size={40}/><h2 className="mt-4 font-display font-bold text-navy">Aún no hay documentos</h2><p className="mt-2 text-sm text-slate-500">Sube una póliza, seguro o certificación para comenzar.</p></div>}{open&&<DocForm clients={data.clients} close={()=>setOpen(false)} reload={data.reload}/>}</div>
}

export default function Admin(){const data=useAdminData();return <AppShell items={nav} admin><Routes><Route index element={<Dashboard data={data}/>}/><Route path="clientes" element={<Clients data={data}/>}/><Route path="reportes" element={<ReportsAdmin data={data}/>}/><Route path="documentos" element={<DocumentsAdmin data={data}/>}/></Routes></AppShell>}
