import { useEffect, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BadgeCheck, CheckCircle2, PhoneCall, ShieldCheck, Snowflake } from 'lucide-react';
import Brand from '../components/Brand';

const services = {
  'hvac-repair': {
    en: { eyebrow: 'HVAC repair & diagnostics', title: 'Clear answers when heating or cooling stops working.', text: 'We diagnose in-suite HVAC problems, explain the cause in plain language and present the appropriate repair options before authorized work begins.', features: ['No cooling or insufficient airflow', 'No heat or uneven temperature', 'Thermostat and control problems', 'Unusual noise, vibration or odour'], steps: ['Describe the problem and suite', 'Technician diagnosis', 'Review available options', 'Repair, test and document'], faq: ['How quickly can a request be reviewed?', 'Urgent requests are prioritized by operations based on the building, symptoms and technician availability.'] },
    fr: { eyebrow: 'Réparation et diagnostic CVCA', title: 'Des réponses claires lorsque le chauffage ou la climatisation cesse de fonctionner.', text: 'Nous diagnostiquons les problèmes CVCA dans les unités, expliquons la cause simplement et présentons les options appropriées avant les travaux autorisés.', features: ['Climatisation insuffisante', 'Absence de chauffage ou température inégale', 'Problèmes de thermostat et de contrôle', 'Bruits, vibrations ou odeurs inhabituels'], steps: ['Décrire le problème et l’unité', 'Diagnostic du technicien', 'Examiner les options', 'Réparer, tester et documenter'], faq: ['À quelle vitesse une demande est-elle examinée?', 'Les demandes urgentes sont priorisées selon l’immeuble, les symptômes et la disponibilité des techniciens.'] }
  },
  'fan-coil-maintenance': {
    en: { eyebrow: 'Fan coil service', title: 'Specialized care for condominium fan coil systems.', text: 'Cleaning, diagnostics and component service designed for fan coils inside occupied condominium suites.', features: ['Filter and coil inspection', 'Drain and condensate checks', 'Valve, actuator and control diagnosis', 'Airflow and operating test'], steps: ['Confirm access and unit', 'Protect the work area', 'Inspect and service components', 'Photograph and report findings'], faq: ['Can service be coordinated across multiple suites?', 'Yes. Building accounts can organize requests and records for multiple suites through one portal.'] },
    fr: { eyebrow: 'Service de ventilo-convecteur', title: 'Un entretien spécialisé pour les ventilo-convecteurs de copropriété.', text: 'Nettoyage, diagnostic et service des composants conçus pour les unités situées dans des copropriétés occupées.', features: ['Inspection du filtre et du serpentin', 'Vérification du drain et du condensat', 'Diagnostic de la vanne et des contrôles', 'Test du débit d’air et du fonctionnement'], steps: ['Confirmer l’accès et l’unité', 'Protéger la zone de travail', 'Inspecter et entretenir', 'Photographier et documenter'], faq: ['Peut-on coordonner plusieurs unités?', 'Oui. Le compte de l’immeuble peut organiser les demandes et les dossiers de plusieurs unités.'] }
  },
  'preventive-maintenance': {
    en: { eyebrow: 'Preventive HVAC maintenance', title: 'Reduce surprises with planned building service.', text: 'A structured maintenance program helps identify developing issues, organize suite access and preserve a complete service history.', features: ['Seasonal equipment checks', 'Filter and coil condition review', 'Operating measurements and observations', 'Building-level maintenance records'], steps: ['Define covered equipment', 'Plan buildings and suites', 'Complete scheduled visits', 'Review findings and priorities'], faq: ['Does maintenance guarantee there will be no failures?', 'No service can eliminate every failure, but planned inspection helps identify risks and improve maintenance decisions.'] },
    fr: { eyebrow: 'Entretien préventif CVCA', title: 'Réduisez les surprises grâce à un service planifié.', text: 'Un programme structuré aide à repérer les problèmes, organiser l’accès aux unités et conserver un historique complet.', features: ['Vérifications saisonnières', 'État du filtre et du serpentin', 'Mesures de fonctionnement', 'Dossiers d’entretien de l’immeuble'], steps: ['Définir les équipements couverts', 'Planifier les unités', 'Effectuer les visites', 'Examiner les priorités'], faq: ['L’entretien empêche-t-il toutes les pannes?', 'Aucun service ne peut éliminer toutes les pannes, mais une inspection planifiée aide à repérer les risques.'] }
  },
  'air-conditioning': {
    en: { eyebrow: 'Air conditioning service', title: 'Reliable cooling for suites and residential buildings.', text: 'Diagnostics, repair and replacement support for air-conditioning equipment serving condominium and residential spaces.', features: ['Cooling performance diagnosis', 'Thermostat and airflow checks', 'Authorized component repair', 'Equipment replacement planning'], steps: ['Report the cooling symptoms', 'Inspect the system', 'Present the recommended scope', 'Restore and verify operation'], faq: ['Do you repair before receiving approval?', 'When authorization is required, the options and cost are presented before the approved work proceeds.'] },
    fr: { eyebrow: 'Service de climatisation', title: 'Une climatisation fiable pour les unités et immeubles résidentiels.', text: 'Diagnostic, réparation et remplacement des équipements de climatisation pour copropriétés et espaces résidentiels.', features: ['Diagnostic de performance', 'Vérification du thermostat et du débit d’air', 'Réparation autorisée des composants', 'Planification du remplacement'], steps: ['Signaler les symptômes', 'Inspecter le système', 'Présenter les travaux recommandés', 'Rétablir et vérifier'], faq: ['Réparez-vous avant l’autorisation?', 'Lorsqu’une autorisation est requise, les options et le coût sont présentés avant les travaux.'] }
  },
  'heating': {
    en: { eyebrow: 'Heating service', title: 'Practical heating diagnostics for dependable comfort.', text: 'We investigate no-heat and uneven-temperature complaints and document the work for property management.', features: ['No-heat diagnosis', 'Thermostat and control review', 'Airflow and fan operation', 'Plain-language service reporting'], steps: ['Create the service request', 'Confirm symptoms and access', 'Diagnose and authorize', 'Repair and final report'], faq: ['Can residents explain the problem without technical terms?', 'Yes. Everyday descriptions are enough for the operations team to begin reviewing the request.'] },
    fr: { eyebrow: 'Service de chauffage', title: 'Un diagnostic pratique pour un confort fiable.', text: 'Nous analysons les absences de chauffage et températures inégales et documentons les travaux pour la gestion immobilière.', features: ['Diagnostic d’absence de chauffage', 'Contrôles et thermostat', 'Débit d’air et ventilateur', 'Rapport en langage simple'], steps: ['Créer la demande', 'Confirmer les symptômes et l’accès', 'Diagnostiquer et autoriser', 'Réparer et produire le rapport'], faq: ['Peut-on décrire le problème sans termes techniques?', 'Oui. Une description simple suffit pour commencer l’analyse.'] }
  },
  'condominium-hvac': {
    en: { eyebrow: 'Condominium HVAC services', title: 'One service process for every suite in the building.', text: 'Purpose-built coordination for property managers handling requests, quotes, appointments, evidence and service history across multiple units.', features: ['Building and suite-level requests', 'Quote approval workflow', 'Technician scheduling and evidence', 'Reports, payments and documents'], steps: ['Building reports the issue', 'Operations reviews and quotes', 'Technician completes authorized scope', 'Client receives the final record'], faq: ['Who owns the client account?', 'The account belongs to the authorized building or property management contact and can cover multiple suites.'] },
    fr: { eyebrow: 'Services CVCA pour copropriétés', title: 'Un processus unique pour toutes les unités de l’immeuble.', text: 'Une coordination conçue pour les gestionnaires qui suivent les demandes, soumissions, rendez-vous, preuves et historiques de plusieurs unités.', features: ['Demandes par immeuble et unité', 'Approbation des soumissions', 'Planification et preuves', 'Rapports, paiements et documents'], steps: ['L’immeuble signale le problème', 'Les opérations analysent et proposent', 'Le technicien effectue les travaux autorisés', 'Le client reçoit le dossier final'], faq: ['À qui appartient le compte client?', 'Le compte appartient au contact autorisé de l’immeuble ou de la gestion et peut couvrir plusieurs unités.'] }
  }
};

export default function ServicePage() {
  const { slug } = useParams();
  const [lang, setLang] = useState('en');
  const record = services[slug];
  const service = record?.[lang];

  useEffect(() => {
    if (!service) return;
    document.title = `${service.eyebrow} | Seals HVAC Toronto`;
    const description = document.querySelector('meta[name="description"]');
    if (description) description.setAttribute('content', service.text);
    window.scrollTo(0, 0);
  }, [service]);

  if (!record) return <Navigate to="/" replace />;

  return <div className="min-h-screen bg-white text-navy">
    <header className="absolute inset-x-0 top-0 z-20 border-b border-white/15"><div className="container-wide flex h-20 items-center justify-between"><Brand light compact/><div className="flex items-center gap-3"><button onClick={() => setLang(lang === 'en' ? 'fr' : 'en')} className="rounded-full border border-white/30 px-4 py-2 text-xs font-extrabold text-white">{lang === 'en' ? 'FR' : 'EN'}</button><a href="tel:+14167328025" className="hidden items-center gap-2 text-xs font-extrabold text-white sm:flex"><PhoneCall size={15}/>416-732-8025</a></div></div></header>
    <main>
      <section className="relative overflow-hidden bg-navy pb-24 pt-36 text-white md:pb-32 md:pt-44"><img src="/images/seals-service-proof-v2.webp" alt="Seals HVAC service" className="absolute inset-0 h-full w-full object-cover opacity-25"/><div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/90 to-navy/35"/><Snowflake className="absolute -right-20 -top-12 h-80 w-80 text-cyan/10"/><div className="container-site relative"><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold text-white/60 hover:text-cyan"><ArrowLeft size={15}/>{lang === 'en' ? 'Back to website' : 'Retour au site'}</Link><p className="mt-14 text-[10px] font-extrabold uppercase tracking-[.22em] text-cyan">{service.eyebrow}</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-extrabold leading-[.98] tracking-[-.055em] md:text-7xl">{service.title}</h1><p className="mt-7 max-w-3xl text-base leading-8 text-white/65 md:text-xl md:leading-9">{service.text}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/#contact" className="inline-flex items-center justify-center gap-2 rounded-full bg-cyan px-7 py-4 text-sm font-extrabold text-navy">{lang === 'en' ? 'Request service' : 'Demander un service'}<ArrowRight size={16}/></a><a href="tel:+14167328025" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/25 px-7 py-4 text-sm font-extrabold text-white"><PhoneCall size={16}/>416-732-8025</a></div></div></section>
      <section className="py-20 md:py-28"><div className="container-site grid gap-12 lg:grid-cols-2"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-brand-600">{lang === 'en' ? 'Common service needs' : 'Besoins courants'}</p><h2 className="mt-5 font-display text-4xl font-extrabold tracking-[-.04em]">{lang === 'en' ? 'Focused on the problem in front of you.' : 'Centré sur votre problème actuel.'}</h2><div className="mt-8 grid gap-3">{service.features.map(item => <p key={item} className="flex items-center gap-3 rounded-xl bg-cloud p-4 text-sm font-bold"><BadgeCheck className="text-brand-600" size={19}/>{item}</p>)}</div></div><div className="rounded-[28px] bg-[#f0f6f9] p-7 md:p-10"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-brand-600">{lang === 'en' ? 'How service moves forward' : 'Déroulement du service'}</p><div className="mt-8 space-y-5">{service.steps.map((item,index)=><div key={item} className="flex gap-4 border-b border-slate-200 pb-5 last:border-0"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-navy text-xs font-black text-cyan">0{index+1}</span><p className="pt-2 font-display font-extrabold">{item}</p></div>)}</div></div></div></section>
      <section className="bg-navy py-20 text-white"><div className="container-site grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-cyan">{lang === 'en' ? 'Clear expectations' : 'Attentes claires'}</p><h2 className="mt-4 max-w-3xl font-display text-3xl font-extrabold md:text-5xl">{service.faq[0]}</h2><p className="mt-5 max-w-3xl text-sm leading-7 text-white/60">{service.faq[1]}</p></div><ShieldCheck className="h-24 w-24 text-cyan/35"/></div></section>
    </main>
    <footer className="bg-[#020e18] py-10 text-white"><div className="container-wide flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><Brand light compact/><p className="text-xs text-white/40">Toronto · North York · GTA · 416-732-8025</p></div></footer>
  </div>;
}
